# This file is for custom makefile variable at the project level.
# They are meant to be share by the whole project team.

APP_VERSION := 0.0.0
APPLICATION_NAME := learning_to_run_a_power_network
CONDA_ENVIRONMENT := grid2op-env
PYTHON_VERSION := 3.11